version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=schedule_reservation_system
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        ENV_FILE_PATH: ${ENV_FILE_PATH}
    container_name: schedule_reservation_system
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=schedule_reservation_system
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db

volumes:
  postgres_data: