default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] || "schedule_reservation_system" %>
  min_messages: error

test:
  <<: *default
  database: <%= ENV["DB_NAME"] || "schedule_reservation_system_test" %>
  min_message: log

